function TermsOfUse() {
  return (
    <main className="flex z-0 flex-col w-full max-md:max-w-full text-black-600 p-6 privacy-policy">
      <header className="flex flex-col justify-center w-full max-md:max-w-full">
        <h1 className="text-3xl font-semibold max-md:max-w-full">
          Terms of Service
        </h1>

        <p className="mt-3 text-base max-md:max-w-full">
          Welcome to Gurubase! These Terms of Service (&quot;Terms&quot;) govern
          your access to and use of the website located at gurubase.io
          (&quot;Gurubase,&quot; &quot;we,&quot; &quot;us,&quot; or
          &quot;our&quot;). By accessing or using Gurubase, you agree to comply
          with these Terms. If you do not agree with these Terms, you may not
          use Gurubase.
        </p>
      </header>

      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          1. Acceptance of Terms
        </h2>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        By using Gurubase, you agree to be bound by these Terms and our Privacy
        Policy. If you are using Gurubase on behalf of an organization, you
        agree to these Terms on behalf of that organization.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          2. Use of Content
        </h2>
      </section>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          2.1 Content Sources and License for Generated Content
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        Gurubase generates content by aggregating and processing information
        from various sources, including user contributions and third-party
        platforms such as{" "}
        <a
          href="https://stackoverflow.com/"
          className="underline"
          target="_blank">
          Stack Overflow
        </a>, and{" "}
        <a
          href="https://www.github.com/"
          className="underline"
          target="_blank">
          GitHub
        </a>
        . The license for any generated content
        will align with the license of the original source(s) used to create that
        content. For example, if content uses sources from Stack Overflow is licensed under the{" "}
        <a
          href="https://creativecommons.org/licenses/by-sa/4.0/"
          className="underline"
          target="_blank">
          Creative Commons Attribution-ShareAlike 4.0 International License (CC
          BY-SA 4.0)
        </a>
        .
      </div>

      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h4 className="font-semibold max-md:max-w-full">
          2.2 Attribution
        </h4>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        All generated content will include appropriate attribution to the original sources, in accordance with their respective licenses. This attribution may appear under a section titled &quot;Sources&quot; or a similar heading.
        For example, if content generated by Gurubase is based on or includes information
        from Stack Overflow, an attribution section will be provide links to the original Stack Overflow posts.
        
        The title and position of this
        attribution section may change in the future. Regardless of these
        changes, Gurubase will always provide proper attribution to the original
        authors.
      </div>

      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          3. User Contributions
        </h2>
      </section>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          3.1 License Grant
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        By submitting content to Gurubase, you grant us a worldwide, perpetual,
        royalty-free, non-exclusive license to use, reproduce, modify,
        distribute, display, and create derivative works of your content in any
        form and media, including for commercial purposes.
      </div>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          3.2 Compliance with Laws
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        You agree that you are responsible for your own conduct and content
        while using Gurubase and for any consequences thereof. You agree to use
        Gurubase only for purposes that are legal, proper, and in accordance
        with these Terms and any applicable laws or regulations.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          4. Intellectual Property
        </h2>
      </section>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          4.1 Gurubase Content
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        All materials displayed or performed on Gurubase, including but not
        limited to text, graphics, logos, tools, photographs, images, software,
        source code, audio, and video (collectively &quot;Gurubase
        Content&quot;), are the property of Gurubase or its licensors and are
        protected by copyright, trademark, and other intellectual property laws.
      </div>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          4.2 Third-Party Content
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        Content from third-party platforms, such as Stack Overflow, is used in
        compliance with the applicable licenses, including CC BY-SA 4.0. Users
        must adhere to these licenses when using or redistributing content
        obtained from Gurubase.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">5. Cookies</h2>
      </section>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          5.1 Use of Cookies
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        Gurubase uses cookies and similar tracking technologies to enhance your
        experience on our site. Cookies are small data files that are stored on
        your device when you visit a website. We use cookies to understand how
        you interact with our site, to improve our services, and to personalize
        your experience.
      </div>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          5.2 Managing Cookies
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        You can manage your cookie preferences through your web browser
        settings. Most browsers allow you to block or delete cookies, but doing
        so may impact your ability to use some features of Gurubase.
      </div>
      <section className="flex flex-col justify-center mt-5 w-full max-md:max-w-full">
        <h3 className="font-semibold max-md:max-w-full">
          5.3 Third-Party Cookies
        </h3>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        We may also use third-party cookies for analytics, advertising, and
        other purposes. These cookies are governed by the privacy policies of
        the third parties that place them. For more detailed information about
        our use of cookies, please refer to our Privacy Policy.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          6. Disclaimer of Warranties
        </h2>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        Gurubase is provided &quot;as is&quot; and &quot;as available&quot;
        without any warranties of any kind, express or implied. We do not
        warrant that the site will be uninterrupted or error-free, nor do we
        make any warranty as to the results that may be obtained from using the
        site.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          7. Limitation of Liability
        </h2>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        To the maximum extent permitted by law, Gurubase and its affiliates,
        officers, employees, agents, and licensors shall not be liable for any
        indirect, incidental, special, consequential, or punitive damages, or
        any loss of profits or revenues, whether incurred directly or
        indirectly, or any loss of data, use, goodwill, or other intangible
        losses resulting from (i) your use of or inability to use Gurubase; (ii)
        any unauthorized access to or use of our servers and/or any personal
        information stored therein; (iii) any interruption or cessation of
        transmission to or from Gurubase; or (iv) any bugs, viruses, trojan
        horses, or the like that may be transmitted to or through our services
        by any third party.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          8. Indemnification
        </h2>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        You agree to indemnify, defend, and hold harmless Gurubase, its
        officers, directors, employees, agents, licensors, and suppliers from
        and against all claims, losses, expenses, damages, and costs, including
        reasonable attorneys&apos; fees, resulting from any violation of these
        Terms or any activity related to your account (including negligent or
        wrongful conduct) by you or any other person accessing Gurubase using
        your account.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          9. Changes to Terms
        </h2>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        We reserve the right to modify these Terms at any time. If we make
        changes to these Terms, we will provide notice of such changes by
        posting the updated Terms on our website.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          10. Governing Law and Dispute Resolution
        </h2>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        These Terms shall be governed by and construed in accordance with the
        laws of the State of Delaware, without regard to its conflict of law
        principles. Any dispute arising out of or relating to these Terms or
        your use of Gurubase shall be resolved through binding arbitration in
        Wilmington, Delaware, in accordance with the rules of the American
        Arbitration Association.
      </div>
      <section className="flex flex-col justify-center mt-10 w-full max-md:max-w-full">
        <h2 className="text-xl font-semibold max-md:max-w-full">
          11. Contact Information
        </h2>
      </section>
      <div className="mt-3 text-base max-md:max-w-full">
        If you have any questions about these Terms, please contact us at
        <a href="mailto:contact@gurubase.io" className="underline ml-1">
          contact@gurubase.io
        </a>
        .
      </div>
    </main>
  );
}

export default TermsOfUse;
