name: selfhosted-dev-gurubase

services:
  milvus:
    image: milvusdb/milvus:v2.4.17
    container_name: selfhosted-dev-gurubase-milvus-standalone
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      COMMON_STORAGETYPE: local
    volumes:
      - ./.devdata/selfhosted/milvus:/var/lib/milvus
    restart: always

  rabbitmq:
    image: rabbitmq:3.13.7-alpine
    container_name: selfhosted-dev-gurubase-rabbitmq
    restart: always

  postgres:
    image: postgres:16.3-alpine
    container_name: selfhosted-dev-gurubase-postgres
    environment:
      POSTGRES_DB: gurubase
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: postgres
    volumes:
      - ./.devdata/selfhosted/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2.6-alpine
    container_name: selfhosted-dev-gurubase-redis
    volumes:
      - ./.devdata/selfhosted/redis:/data
    restart: always

  nginx:
    image: nginx:1.23.3-alpine
    container_name: selfhosted-dev-gurubase-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.devdata/selfhosted/backend_media:/django_media_files
    ports:
      - "8019:8019"
    restart: always

networks:
  default:
    name: selfhosted-dev-gurubase