# Generated by Django 4.2.18 on 2025-04-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0082_gurutype_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DISCORD', 'DISCORD'), ('SLACK', 'SLACK'), ('GITHUB', 'GITHUB'), ('JIRA', 'JIRA'), ('ZENDESK', 'ZENDESK'), ('CONFLUENCE', 'CONFLUENCE')], default='DISCORD', max_length=50)),
                ('workspace_name', models.TextField(blank=True, null=True)),
                ('external_id', models.TextField()),
                ('code', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('channels', models.JSONField(blank=True, default=list, null=False)),
                ('github_private_key', models.TextField(blank=True, null=True)),
                ('github_client_id', models.TextField(blank=True, null=True)),
                ('github_secret', models.TextField(blank=True, null=True)),
                ('github_bot_name', models.TextField(blank=True, null=True)),
                ('github_html_url', models.TextField(blank=True, null=True)),
                ('jira_api_key', models.TextField(blank=True, null=True)),
                ('jira_user_email', models.TextField(blank=True, null=True)),
                ('jira_domain', models.TextField(blank=True, null=True)),
                ('confluence_api_token', models.TextField(blank=True, null=True)),
                ('confluence_user_email', models.TextField(blank=True, null=True)),
                ('confluence_domain', models.TextField(blank=True, null=True)),
                ('zendesk_domain', models.TextField(blank=True, null=True)),
                ('zendesk_api_token', models.TextField(blank=True, null=True)),
                ('zendesk_user_email', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('api_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_owner', to='core.apikey')),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
            ],
            options={
                'unique_together': {('type', 'guru_type')},
            },
        ),
        migrations.CreateModel(
            name='WidgetId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('domain_url', models.URLField(max_length=2000)),
                ('domain', models.URLField(max_length=2000)),
                ('is_wildcard', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_ids', to='core.gurutype')),
            ],
            options={
                'verbose_name': 'Widget ID',
                'verbose_name_plural': 'Widget IDs',
                'unique_together': {('guru_type', 'domain_url')},
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('binge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.binge')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
            options={
                'unique_together': {('thread_id', 'integration')},
            },
        ),
    ]
