# Generated by Django 4.2.18 on 2025-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='allow_dm',
            field=models.BooleanField(default=False),
        ),
    ]
