# Generated by Django 4.2.18 on 2025-02-25 10:53

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid
from urllib.parse import urlparse


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# core.migrations.0034_populate_domain_field

def populate_domain_field(apps, schema_editor):
    WidgetId = apps.get_model('core', 'WidgetId')
    for widget in WidgetId.objects.all():
        parsed_url = urlparse(widget.domain_url)
        widget.domain = f"{parsed_url.scheme}://{parsed_url.netloc}"
        widget.save()

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_gurutype_icon_url'), ('core', '0003_remove_question_unique_binge_slug_guru_and_more'), ('core', '0004_gurutype_github_details_updated_date'), ('core', '0005_alter_question_source_widgetid'), ('core', '0006_rename_saved_similarities_question_similar_questions'), ('core', '0007_remove_question_content_most_similar_and_more'), ('core', '0008_settings_widget_max_length'), ('core', '0009_rename_widget_max_length_settings_widget_answer_max_length'), ('core', '0010_question_user'), ('core', '0010_datasource_private'), ('core', '0011_merge_0010_datasource_private_0010_question_user'), ('core', '0012_gurutype_has_sitemap_added_questions'), ('core', '0013_alter_datasource_type_alter_featureddatasource_type_and_more'), ('core', '0014_githubfile_doc_ids_githubfile_in_milvus'), ('core', '0015_datasource_default_branch'), ('core', '0016_githubfile_link'), ('core', '0013_alter_question_source'), ('core', '0014_apikey'), ('core', '0015_delete_questionvaliditycheckpricing'), ('core', '0017_merge_20250113_1453'), ('core', '0018_questionvaliditycheckpricing'), ('core', '0017_gurutype_index_repo'), ('core', '0019_merge_20250114_1133'), ('core', '0020_apikey_integration_alter_gurutype_index_repo_and_more'), ('core', '0021_integration_code'), ('core', '0022_alter_integration_api_key'), ('core', '0023_integration_refresh_token'), ('core', '0024_thread'), ('core', '0025_integration_workspace_name'), ('core', '0020_alter_gurutype_index_repo'), ('core', '0021_apikey_name'), ('core', '0026_merge_20250123_0913'), ('core', '0027_alter_question_source'), ('core', '0028_alter_integration_unique_together'), ('core', '0020_question_times'), ('core', '0021_merge_20250120_0950'), ('core', '0022_merge_0021_apikey_name_0021_merge_20250120_0950'), ('core', '0029_merge_20250127_0741'), ('core', '0029_merge_20250126_1945'), ('core', '0030_merge_20250128_1227'), ('core', '0031_datasource_scrape_tool'), ('core', '0032_outofcontextquestion_source'), ('core', '0033_settings_openai_api_key'), ('core', '0034_settings_is_openai_key_valid'), ('core', '0033_outofcontextquestion_core_outofc_guru_ty_a23c4d_idx_and_more'), ('core', '0035_merge_20250205_1421'), ('core', '0036_settings_firecrawl_api_key_and_more'), ('core', '0037_alter_settings_scrape_type'), ('core', '0034_populate_domain_field'), ('core', '0038_merge_20250211_1339'), ('core', '0039_gurutype_github_file_count_limit_per_repo_hard_and_more'), ('core', '0040_alter_datasource_unique_together'), ('core', '0041_crawlstate'), ('core', '0042_proxy'), ('core', '0043_remove_proxy_used_for'), ('core', '0044_delete_proxy'), ('core', '0045_crawlstate_guru_type_crawlstate_user'), ('core', '0046_alter_crawlstate_guru_type_alter_crawlstate_user'), ('core', '0047_alter_crawlstate_user'), ('core', '0048_crawlstate_last_polled_at_crawlstate_source')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('WEBSITE', 'WEBSITE'), ('YOUTUBE', 'YOUTUBE')], default='PDF', max_length=50)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.get_datasource_upload_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('in_milvus', models.BooleanField(default=False)),
                ('doc_ids', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('NOT_PROCESSED', 'NOT_PROCESSED'), ('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], default='NOT_PROCESSED', max_length=50)),
                ('error', models.TextField(blank=True, default='')),
                ('content_rewritten', models.BooleanField(default=False)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('initial_summarizations_created', models.BooleanField(default=False)),
                ('final_summarization_created', models.BooleanField(default=False)),
                ('last_reindex_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('reindex_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('favicon_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuruType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('stackoverflow_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('github_repo', models.URLField(blank=True, default='', max_length=2000, null=True)),
                ('github_details', models.JSONField(blank=True, default=dict)),
                ('colors', models.JSONField(blank=True, default=dict)),
                ('icon_url', models.URLField(blank=True, default='', max_length=2000, null=True)),
                ('ogimage_url', models.URLField(blank=True, default='', max_length=2000, null=True)),
                ('ogimage_base_url', models.URLField(blank=True, default='', max_length=2000, null=True)),
                ('stackoverflow_source', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('intro_text', models.TextField(blank=True, default='', null=True)),
                ('custom', models.BooleanField(default=True)),
                ('milvus_collection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('typesense_collection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_knowledge', models.TextField(blank=True, default='', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('maintainers', models.ManyToManyField(blank=True, related_name='maintained_guru_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkValidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('valid', models.BooleanField(default=False)),
                ('response_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1500)),
                ('question', models.TextField()),
                ('old_question', models.TextField(blank=True, default='', null=True)),
                ('user_question', models.TextField(blank=True, default='', null=True)),
                ('og_image_url', models.URLField(blank=True, default='', max_length=2000, null=True)),
                ('content', models.TextField()),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField()),
                ('change_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('add_to_sitemap', models.BooleanField(default=False)),
                ('sitemap_reason', models.TextField(blank=True, default='', null=True)),
                ('sitemap_date', models.DateTimeField(blank=True, null=True)),
                ('description_similarity_percent', models.FloatField(blank=True, null=True)),
                ('title_similarity_percent', models.FloatField(blank=True, null=True)),
                ('content_similarity_percent', models.FloatField(blank=True, null=True)),
                ('saved_similarities', models.JSONField(blank=True, default=dict)),
                ('context_distances', models.JSONField(blank=True, default=list)),
                ('reranked_scores', models.JSONField(blank=True, default=list)),
                ('default_question', models.BooleanField(default=False)),
                ('cost_dollars', models.FloatField(blank=True, default=0, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cached_prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('latency_sec', models.FloatField(blank=True, default=0, null=True)),
                ('source', models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION')], default='USER', max_length=50)),
                ('references', models.JSONField(blank=True, default=dict, null=True)),
                ('prompt', models.TextField(blank=True, default='', null=True)),
                ('english', models.BooleanField(default=True)),
                ('title_processed', models.BooleanField(default=False)),
                ('llm_eval', models.BooleanField(default=False)),
                ('similarity_written_to_milvus', models.BooleanField(default=False)),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('cache_request_count', models.IntegerField(default=0)),
                ('trust_score', models.FloatField(blank=True, default=0, null=True)),
                ('processed_ctx_relevances', models.JSONField(blank=True, default=dict)),
                ('llm_usages', models.JSONField(blank=True, default=dict)),
                ('binge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.binge')),
                ('content_most_similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_similar_questions', to='core.question')),
                ('description_most_similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='description_similar_questions', to='core.question')),
                ('guru_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gurutype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_question', to='core.question')),
                ('title_most_similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='title_similar_questions', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionValidityCheckPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1500)),
                ('cost_dollars', models.FloatField(blank=True, default=0, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cached_prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rerank_threshold', models.FloatField(default=0.01)),
                ('rerank_threshold_llm_eval', models.FloatField(default=0.01)),
                ('trust_score_threshold', models.FloatField(default=0.0)),
                ('pricings', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Summarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_data_source_summarization', models.BooleanField(default=True)),
                ('content_metadata', models.JSONField(blank=True, default=list, null=True)),
                ('initial', models.BooleanField(default=False)),
                ('source_content', models.TextField(blank=True, null=True)),
                ('split_num', models.IntegerField(default=1)),
                ('result_content', models.TextField(blank=True, null=True)),
                ('is_root', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('summary_suitable', models.BooleanField(default=False)),
                ('reasoning', models.TextField(blank=True, default='', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('model', models.TextField(default='gpt-4o-2024-08-06')),
                ('usages', models.JSONField(blank=True, default=dict, null=True)),
                ('data_source_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datasource')),
                ('guru_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryQuestionGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_sufficient', models.BooleanField(default=False)),
                ('questions', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('model', models.TextField(default='gpt-4o-2024-08-06')),
                ('usages', models.JSONField(blank=True, default=dict, null=True)),
                ('guru_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question')),
                ('summarization_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.summarization')),
            ],
        ),
        migrations.AddField(
            model_name='summarization',
            name='question_generation_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.summaryquestiongeneration'),
        ),
        migrations.AddField(
            model_name='summarization',
            name='summarization_refs',
            field=models.ManyToManyField(blank=True, to='core.summarization'),
        ),
        migrations.CreateModel(
            name='RawQuestionGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.TextField()),
                ('page_num', models.IntegerField()),
                ('page_size', models.IntegerField()),
                ('generate_count', models.IntegerField()),
                ('model', models.TextField()),
                ('cost_dollars', models.FloatField(blank=True, default=0, null=True)),
                ('prompts', models.JSONField(blank=True, default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('guru_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gurutype')),
            ],
        ),
        migrations.CreateModel(
            name='RawQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('guru_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gurutype')),
                ('raw_question_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawquestiongeneration')),
            ],
        ),
        migrations.CreateModel(
            name='OutOfContextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_question', models.TextField()),
                ('rerank_threshold', models.FloatField(default=0.0)),
                ('trust_score_threshold', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('processed_ctx_relevances', models.JSONField(blank=True, default=dict)),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
            ],
        ),
        migrations.CreateModel(
            name='LLMEvalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('model', models.TextField()),
                ('context_relevance_avg', models.FloatField()),
                ('context_relevance_median', models.FloatField()),
                ('context_relevance_std', models.FloatField()),
                ('groundedness_avg', models.FloatField()),
                ('groundedness_median', models.FloatField()),
                ('groundedness_std', models.FloatField()),
                ('answer_relevance_avg', models.FloatField()),
                ('answer_relevance_median', models.FloatField()),
                ('answer_relevance_std', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('context_relevance_non_zero_avg', models.FloatField(blank=True, null=True)),
                ('context_relevance_non_zero_median', models.FloatField(blank=True, null=True)),
                ('context_relevance_non_zero_std', models.FloatField(blank=True, null=True)),
                ('context_relevance_non_zero_count', models.IntegerField(blank=True, null=True)),
                ('groundedness_non_zero_avg', models.FloatField(blank=True, null=True)),
                ('groundedness_non_zero_median', models.FloatField(blank=True, null=True)),
                ('groundedness_non_zero_std', models.FloatField(blank=True, null=True)),
                ('groundedness_non_zero_count', models.IntegerField(blank=True, null=True)),
                ('answer_relevance_non_zero_avg', models.FloatField(blank=True, null=True)),
                ('answer_relevance_non_zero_median', models.FloatField(blank=True, null=True)),
                ('answer_relevance_non_zero_std', models.FloatField(blank=True, null=True)),
                ('answer_relevance_non_zero_count', models.IntegerField(blank=True, null=True)),
                ('plot_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
            ],
        ),
        migrations.CreateModel(
            name='LLMEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('context_relevance', models.FloatField(blank=True, default=0, null=True)),
                ('context_relevance_cot', models.TextField(blank=True, default='', null=True)),
                ('context_relevance_prompt', models.TextField(blank=True, default='', null=True)),
                ('context_relevance_user_prompt', models.TextField(blank=True, default='', null=True)),
                ('groundedness', models.FloatField(blank=True, default=0, null=True)),
                ('groundedness_cot', models.TextField(blank=True, default='', null=True)),
                ('groundedness_prompt', models.TextField(blank=True, default='', null=True)),
                ('answer_relevance', models.FloatField(blank=True, default=0, null=True)),
                ('answer_relevance_cot', models.TextField(blank=True, default='', null=True)),
                ('answer_relevance_prompt', models.TextField(blank=True, default='', null=True)),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('reranked_scores', models.JSONField(blank=True, default=list)),
                ('cost_dollars', models.FloatField(blank=True, default=0, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cached_prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prompt', models.TextField(blank=True, default='', null=True)),
                ('contexts', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('processed_ctx_relevances', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_evals', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='LinkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('validity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.linkvalidity')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PDF', 'Pdf'), ('WEBSITE', 'Website'), ('YOUTUBE', 'Youtube')], default='PDF', max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('icon_url', models.URLField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='guru_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gurutype'),
        ),
        migrations.CreateModel(
            name='ContentPageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.question')),
            ],
        ),
        migrations.AddField(
            model_name='binge',
            name='guru_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype'),
        ),
        migrations.AddField(
            model_name='binge',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binge',
            name='root_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binge_root_question', to='core.question'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['add_to_sitemap'], name='core_questi_add_to__7f382b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['guru_type'], name='core_questi_guru_ty_90862d_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('binge', 'slug', 'guru_type'), name='unique_binge_slug_guru'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('binge', 'question', 'guru_type'), name='unique_binge_question_guru'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('binge__isnull', True)), fields=('slug', 'guru_type'), name='unique_null_binge_slug_guru'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('binge__isnull', True)), fields=('question', 'guru_type'), name='unique_null_binge_question_guru'),
        ),
        migrations.AlterUniqueTogether(
            name='llmevalresult',
            unique_together={('guru_type', 'version', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('type', 'url', 'guru_type')},
        ),
        migrations.AlterField(
            model_name='gurutype',
            name='icon_url',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_binge_slug_guru',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_binge_question_guru',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_null_binge_slug_guru',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_null_binge_question_guru',
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_details_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION')], default='USER', max_length=50),
        ),
        migrations.CreateModel(
            name='WidgetId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('domain_url', models.URLField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_ids', to='core.gurutype')),
            ],
            options={
                'verbose_name': 'Widget ID',
                'verbose_name_plural': 'Widget IDs',
                'unique_together': {('guru_type', 'domain_url')},
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='saved_similarities',
            new_name='similar_questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_most_similar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_similarity_percent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_most_similar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_similarity_percent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_most_similar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_similarity_percent',
        ),
        migrations.AddField(
            model_name='settings',
            name='widget_answer_max_length',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='has_sitemap_added_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WEBSITE', 'WEBSITE'), ('YOUTUBE', 'YOUTUBE'), ('GITHUB_REPO', 'GITHUB_REPO')], default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureddatasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('WEBSITE', 'Website'), ('YOUTUBE', 'Youtube'), ('GITHUB_REPO', 'Github Repo')], default='PDF', max_length=50),
        ),
        migrations.AddField(
            model_name='datasource',
            name='default_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GitHubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('content', models.TextField()),
                ('size', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_files', to='core.datasource')),
                ('doc_ids', models.JSONField(blank=True, default=list, null=True)),
                ('in_milvus', models.BooleanField(default=False)),
                ('link', models.URLField(default='asd', max_length=2000)),
            ],
            options={
                'indexes': [models.Index(fields=['path'], name='core_github_path_2d0006_idx')],
                'unique_together': {('data_source', 'path')},
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION'), ('API', 'API')], default='USER', max_length=50),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('integration', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionValidityCheckPricing',
        ),
        migrations.CreateModel(
            name='QuestionValidityCheckPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1500)),
                ('cost_dollars', models.FloatField(blank=True, default=0, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cached_prompt_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gurutype',
            name='index_repo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DISCORD', 'DISCORD'), ('SLACK', 'SLACK')], default='DISCORD', max_length=50)),
                ('external_id', models.TextField()),
                ('access_token', models.TextField()),
                ('channels', models.JSONField(blank=True, default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('api_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_owner', to='core.apikey')),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
                ('code', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('workspace_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('type', 'guru_type')},
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('binge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.binge')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.integration')),
            ],
            options={
                'unique_together': {('thread_id', 'integration')},
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION'), ('API', 'API'), ('DISCORD', 'DISCORD'), ('SLACK', 'SLACK')], default='USER', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='times',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasource',
            name='scrape_tool',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outofcontextquestion',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION'), ('API', 'API'), ('DISCORD', 'DISCORD'), ('SLACK', 'SLACK')], default='USER', max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_openai_key_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='outofcontextquestion',
            index=models.Index(fields=['guru_type', 'date_created'], name='core_outofc_guru_ty_a23c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='outofcontextquestion',
            index=models.Index(fields=['source'], name='core_outofc_source_1328c9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['date_created'], name='core_questi_date_cr_c8d35b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source'], name='core_questi_source_55b1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['guru_type', 'date_created'], name='core_questi_guru_ty_47eb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['guru_type', 'source'], name='core_questi_guru_ty_7690ae_idx'),
        ),
        migrations.AddField(
            model_name='settings',
            name='firecrawl_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_firecrawl_key_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='scrape_type',
            field=models.CharField(choices=[('CRAWL4AI', 'Crawl4AI'), ('FIRECRAWL', 'Firecrawl')], default='CRAWL4AI', max_length=50),
        ),
        migrations.AddField(
            model_name='widgetid',
            name='domain',
            field=models.URLField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_domain_field,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_file_count_limit_per_repo_hard',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_file_count_limit_per_repo_soft',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_repo_count_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_repo_size_limit_mb',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('url', 'guru_type')},
        ),
        migrations.CreateModel(
            name='CrawlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='RUNNING', max_length=50)),
                ('discovered_urls', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('link_limit', models.IntegerField(default=1500)),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_polled_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('UI', 'User Interface'), ('API', 'API')], default='API', max_length=30)),
            ],
        ),
    ]
