# Generated by Django 4.2.13 on 2024-12-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_question_unique_binge_slug_guru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='github_details_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
