# Generated by Django 4.2.13 on 2024-12-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gurutype_github_details_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION')], default='USER', max_length=50),
        ),
        migrations.CreateModel(
            name='WidgetId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('domain_url', models.URLField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_ids', to='core.gurutype')),
            ],
            options={
                'verbose_name': 'Widget ID',
                'verbose_name_plural': 'Widget IDs',
                'unique_together': {('guru_type', 'domain_url')},
            },
        ),
    ]
