# Generated by Django 4.2.13 on 2024-12-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_source_widgetid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='saved_similarities',
            new_name='similar_questions',
        ),
    ]
