# Generated by Django 4.2.13 on 2024-12-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_saved_similarities_question_similar_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content_most_similar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_similarity_percent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_most_similar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_similarity_percent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_most_similar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_similarity_percent',
        ),
    ]
