# Generated by Django 4.2.13 on 2024-12-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_question_content_most_similar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='widget_max_length',
            field=models.IntegerField(default=150),
        ),
    ]
