# Generated by Django 4.2.13 on 2024-12-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_settings_widget_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='widget_max_length',
            new_name='widget_answer_max_length',
        ),
    ]
