# Generated by Django 4.2.13 on 2025-01-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_datasource_private'),
        ('core', '0010_question_user'),
    ]

    operations = [
    ]
