# Generated by Django 4.2.13 on 2025-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_0010_datasource_private_0010_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='has_sitemap_added_questions',
            field=models.BooleanField(default=False),
        ),
    ]
