# Generated by Django 4.2.13 on 2025-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_datasource_type_alter_featureddatasource_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubfile',
            name='doc_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='githubfile',
            name='in_milvus',
            field=models.BooleanField(default=False),
        ),
    ]
