# Generated by Django 4.2.13 on 2025-01-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionValidityCheckPricing',
        ),
    ]
