# Generated by Django 4.2.13 on 2025-01-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_githubfile_doc_ids_githubfile_in_milvus'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='default_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
