# Generated by Django 4.2.13 on 2025-01-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_datasource_default_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubfile',
            name='link',
            field=models.URLField(default='asd', max_length=2000),
            preserve_default=False,
        ),
    ]
