# Generated by Django 4.2.13 on 2025-01-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_questionvaliditycheckpricing'),
        ('core', '0016_githubfile_link'),
    ]

    operations = [
    ]
