# Generated by Django 4.2.13 on 2025-01-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_githubfile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='index_repo',
            field=models.BooleanField(default=False),
        ),
    ]
