# Generated by Django 4.2.13 on 2025-01-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_gurutype_index_repo'),
        ('core', '0018_questionvaliditycheckpricing'),
    ]

    operations = [
    ]
