# Generated by Django 4.2.13 on 2025-01-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20250114_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gurutype',
            name='index_repo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DISCORD', 'DISCORD'), ('SLACK', 'SLACK')], default='DISCORD', max_length=50)),
                ('external_id', models.TextField()),
                ('access_token', models.TextField()),
                ('channels', models.JSONField(blank=True, default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_owner', to='core.apikey')),
                ('guru_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype')),
            ],
            options={
                'unique_together': {('type', 'external_id')},
            },
        ),
    ]
