# Generated by Django 4.2.13 on 2025-01-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20250114_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='times',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
