# Generated by Django 4.2.13 on 2025-01-22 12:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20250114_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurutype',
            name='index_repo',
            field=models.BooleanField(default=True),
        ),
    ]
