# Generated by Django 4.2.13 on 2025-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_gurutype_index_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
