# Generated by Django 4.2.13 on 2025-01-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_gurutype_index_repo'),
        ('core', '0020_question_times'),
    ]

    operations = [
    ]
