# Generated by Django 4.2.13 on 2025-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_apikey_integration_alter_gurutype_index_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
