# Generated by Django 4.2.13 on 2025-01-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_integration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_owner', to='core.apikey'),
        ),
    ]
