# Generated by Django 4.2.13 on 2025-01-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_apikey_name'),
        ('core', '0021_merge_20250120_0950'),
    ]

    operations = [
    ]
