# Generated by Django 4.2.13 on 2025-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_integration_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
