# Generated by Django 4.2.13 on 2025-01-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_integration_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('binge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.binge')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.integration')),
            ],
            options={
                'unique_together': {('thread_id', 'integration')},
            },
        ),
    ]
