# Generated by Django 4.2.13 on 2025-01-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='workspace_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
