# Generated by Django 4.2.13 on 2025-01-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_apikey_name'),
        ('core', '0025_integration_workspace_name'),
    ]

    operations = [
    ]
