# Generated by Django 4.2.13 on 2025-01-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20250123_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION'), ('API', 'API'), ('DISCORD', 'DISCORD'), ('SLACK', 'SLACK')], default='USER', max_length=50),
        ),
    ]
