# Generated by Django 4.2.13 on 2025-01-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_question_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('type', 'guru_type')},
        ),
    ]
