# Generated by Django 4.2.18 on 2025-01-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_0021_apikey_name_0021_merge_20250120_0950'),
        ('core', '0028_alter_integration_unique_together'),
    ]

    operations = [
    ]
