# Generated by Django 4.2.13 on 2025-01-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20250126_1945'),
        ('core', '0029_merge_20250127_0741'),
    ]

    operations = [
    ]
