# Generated by Django 4.2.18 on 2025-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20250128_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='scrape_tool',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
