# Generated by Django 4.2.18 on 2025-02-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_outofcontextquestion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
