# Generated by Django 4.2.18 on 2025-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_settings_openai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_openai_key_valid',
            field=models.BooleanField(default=False),
        ),
    ]
