# Generated by Django 4.2.18 on 2025-02-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_outofcontextquestion_core_outofc_guru_ty_a23c4d_idx_and_more'),
        ('core', '0034_settings_is_openai_key_valid'),
    ]

    operations = [
    ]
