# Generated by Django 4.2.18 on 2025-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20250205_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='firecrawl_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_firecrawl_key_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='scrape_type',
            field=models.CharField(choices=[('CRAWL4AI', 'Crawl4AI'), ('FIRECRAWL', 'Firecrawl')], default='FIRECRAWL', max_length=50),
        ),
    ]
