# Generated by Django 4.2.18 on 2025-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_settings_firecrawl_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='scrape_type',
            field=models.CharField(choices=[('CRAWL4AI', 'Crawl4AI'), ('FIRECRAWL', 'Firecrawl')], default='CRAWL4AI', max_length=50),
        ),
    ]
