# Generated by Django 4.2.18 on 2025-02-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_populate_domain_field'),
        ('core', '0037_alter_settings_scrape_type'),
    ]

    operations = [
    ]
