# Generated by Django 4.2.18 on 2025-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20250211_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='github_file_count_limit_per_repo_hard',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_file_count_limit_per_repo_soft',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_repo_count_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='github_repo_size_limit_mb',
            field=models.IntegerField(default=100),
        ),
    ]
