# Generated by Django 4.2.18 on 2025-02-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_gurutype_github_file_count_limit_per_repo_hard_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('url', 'guru_type')},
        ),
    ]
