# Generated by Django 4.2.18 on 2025-02-19 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_crawlstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ('country', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
                ('location_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField()),
                ('is_locked', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('used_for', models.CharField(choices=[('load', 'Load'), ('latency', 'Latency')], default='load', max_length=30)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('address', 'port', 'username')},
            },
        ),
    ]
