# Generated by Django 4.2.18 on 2025-02-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='used_for',
        ),
    ]
