# Generated by Django 4.2.18 on 2025-02-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_proxy_used_for'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proxy',
        ),
    ]
