# Generated by Django 4.2.18 on 2025-02-21 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_crawlstate_guru_type_crawlstate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlstate',
            name='guru_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gurutype'),
        ),
        migrations.AlterField(
            model_name='crawlstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
