# Generated by Django 4.2.18 on 2025-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_crawlstate_last_polled_at_crawlstate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_successful_index_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
