# Generated by Django 4.2.18 on 2025-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_convert_github_repo_to_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurutype',
            name='github_repos',
            field=models.JSONField(default=list),
        ),
    ]
