# Generated by Django 4.2.18 on 2025-02-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_crawlstate_last_polled_at_crawlstate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='pdf_size_limit_mb',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='website_count_limit',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='youtube_count_limit',
            field=models.IntegerField(default=100),
        ),
    ]
