# Generated by Django 4.2.18 on 2025-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_gurutype_pdf_size_limit_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_successful_index_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
