# Generated by Django 4.2.18 on 2025-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_datasource_last_successful_index_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='user_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
