# Generated by Django 4.2.18 on 2025-03-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_datasource_user_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurutype',
            name='github_repos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
