# Generated by Django 4.2.18 on 2025-03-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_gurutype_github_repos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlstate',
            name='guru_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gurutype'),
        ),
    ]
