# Generated by Django 4.2.18 on 2025-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_gurutype_github_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetid',
            name='is_wildcard',
            field=models.BooleanField(default=False),
        ),
    ]
