# Generated by Django 4.2.18 on 2025-03-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_crawlstate_guru_type'),
        ('core', '0057_widgetid_is_wildcard'),
    ]

    operations = [
    ]
