# Generated by Django 4.2.18 on 2025-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_gurucreationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurucreationform',
            name='source',
            field=models.CharField(default='/', max_length=50),
            preserve_default=False,
        ),
    ]
