# Generated by Django 4.2.18 on 2025-03-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_widgetid_is_wildcard'),
        ('core', '0058_gurucreationform_source'),
    ]

    operations = [
    ]
