# Generated by Django 4.2.18 on 2025-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_gurutype_code_embedding_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofcontextquestion',
            name='parent_topics',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_topics',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
