# Generated by Django 4.2.18 on 2025-03-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_gurutype_code_embedding_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_embedding_model',
            field=models.CharField(choices=[('IN_HOUSE', 'In-house embedding model'), ('OPENAI_TEXT_EMBEDDING_3_SMALL', 'OpenAI - text-embedding-3-small')], default='IN_HOUSE', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='embedding_model_configs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='gurutype',
            name='code_embedding_model',
            field=models.CharField(choices=[('IN_HOUSE', 'In-house embedding model'), ('GEMINI_EMBEDDING_001', 'Gemini - embedding-001'), ('GEMINI_TEXT_EMBEDDING_004', 'Gemini - text-embedding-004'), ('OPENAI_TEXT_EMBEDDING_3_SMALL', 'OpenAI - text-embedding-3-small'), ('OPENAI_TEXT_EMBEDDING_3_LARGE', 'OpenAI - text-embedding-3-large'), ('OPENAI_TEXT_EMBEDDING_ADA_002', 'OpenAI - text-embedding-ada-002')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='gurutype',
            name='text_embedding_model',
            field=models.CharField(choices=[('IN_HOUSE', 'In-house embedding model'), ('GEMINI_EMBEDDING_001', 'Gemini - embedding-001'), ('GEMINI_TEXT_EMBEDDING_004', 'Gemini - text-embedding-004'), ('OPENAI_TEXT_EMBEDDING_3_SMALL', 'OpenAI - text-embedding-3-small'), ('OPENAI_TEXT_EMBEDDING_3_LARGE', 'OpenAI - text-embedding-3-large'), ('OPENAI_TEXT_EMBEDDING_ADA_002', 'OpenAI - text-embedding-ada-002')], default=None, max_length=100),
        ),
    ]
