# Generated by Django 4.2.18 on 2025-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_outofcontextquestion_parent_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofcontextquestion',
            name='rephrasings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='rephrasings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
