# Generated by Django 4.2.18 on 2025-03-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_outofcontextquestion_rephrasings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outofcontextquestion',
            name='rephrasings',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rephrasings',
        ),
        migrations.AddField(
            model_name='outofcontextquestion',
            name='enhanced_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='enhanced_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
