# Generated by Django 4.2.18 on 2025-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_outofcontextquestion_parent_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_youtube_key_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
