# Generated by Django 4.2.18 on 2025-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_update_guru_types_embedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_embedding_model',
            field=models.CharField(choices=[('IN_HOUSE', 'In-house embedding model'), ('OPENAI_TEXT_EMBEDDING_3_SMALL', 'OpenAI - text-embedding-3-small')], default='OPENAI_TEXT_EMBEDDING_3_SMALL', max_length=100),
        ),
    ]
