# Generated by Django 4.2.18 on 2025-03-13 12:43

from django.db import migrations
from django.conf import settings


def set_default_embedding_model(apps, schema_editor):
    Settings = apps.get_model('core', 'Settings')
    for setting in Settings.objects.all():
        setting.default_embedding_model = "IN_HOUSE" if settings.ENV != 'selfhosted' else "OPENAI_TEXT_EMBEDDING_3_SMALL"
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_settings_default_embedding_model'),
    ]

    operations = [
        migrations.RunPython(set_default_embedding_model, reverse_code=migrations.RunPython.noop),
    ]
