# Generated by Django 4.2.18 on 2025-03-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_outofcontextquestion_rephrasings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outofcontextquestion',
            name='parent_topics',
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent_topics',
        ),
    ]
