# Generated by Django 4.2.18 on 2025-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20250313_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_embedding_model',
            field=models.CharField(blank=True, choices=[('IN_HOUSE', 'In-house embedding model'), ('OPENAI_TEXT_EMBEDDING_3_SMALL', 'OpenAI - text-embedding-3-small')], default=None, max_length=100, null=True),
        ),
    ]
