# Generated by Django 4.2.18 on 2025-03-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_settings_code_file_extensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
