# Generated by Django 4.2.18 on 2025-03-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_settings_code_file_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('DISCORD', 'DISCORD'), ('SLACK', 'SLACK'), ('GITHUB', 'GITHUB')], default='DISCORD', max_length=50),
        ),
        migrations.AlterField(
            model_name='outofcontextquestion',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION'), ('API', 'API'), ('DISCORD', 'DISCORD'), ('SLACK', 'SLACK'), ('GITHUB', 'GITHUB')], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('USER', 'USER'), ('RAW_QUESTION', 'RAW_QUESTION'), ('REDDIT', 'REDDIT'), ('SUMMARY QUESTION', 'SUMMARY QUESTION'), ('WIDGET QUESTION', 'WIDGET QUESTION'), ('API', 'API'), ('DISCORD', 'DISCORD'), ('SLACK', 'SLACK'), ('GITHUB', 'GITHUB')], default='USER', max_length=50),
        ),
    ]
