# Generated by Django 4.2.18 on 2025-04-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_integration_type_and_more'),
        ('core', '0067_gurutype_send_notification'),
    ]

    operations = [
    ]
