# Generated by Django 4.2.18 on 2025-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_merge_20250402_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='github_client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='github_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
