# Generated by Django 4.2.18 on 2025-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_integration_github_bot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='github_html_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
