# Generated by Django 4.2.18 on 2025-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_integration_github_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='github_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
