# Generated by Django 4.2.18 on 2025-04-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_integration_github_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='github_glob_include',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='github_glob_pattern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
