# Generated by Django 4.2.18 on 2025-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_integration_github_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='github_bot_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
