# Generated by Django 4.2.18 on 2025-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_datasource_github_glob_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ai_provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('OLLAMA', 'Ollama')], default='OPENAI', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_base_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_embedding_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
