# Generated by Django 4.2.18 on 2025-04-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_datasource_github_glob_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='jira_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='jira_domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='jira_user_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('DISCORD', 'DISCORD'), ('SLACK', 'SLACK'), ('GITHUB', 'GITHUB'), ('JIRA', 'JIRA')], default='DISCORD', max_length=50),
        ),
    ]
