# Generated by Django 4.2.18 on 2025-04-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_settings_ai_provider_settings_ollama_base_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='ai_provider',
            new_name='ai_model_provider',
        ),
    ]
