# Generated by Django 4.2.18 on 2025-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_integration_jira_api_key_integration_jira_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='jira_count_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WEBSITE', 'WEBSITE'), ('YOUTUBE', 'YOUTUBE'), ('GITHUB_REPO', 'GITHUB_REPO'), ('JIRA', 'JIRA')], default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureddatasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('WEBSITE', 'Website'), ('YOUTUBE', 'Youtube'), ('GITHUB_REPO', 'Github Repo'), ('JIRA', 'Jira')], default='PDF', max_length=50),
        ),
    ]
