# Generated by Django 4.2.18 on 2025-04-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_gurutype_jira_count_limit_alter_datasource_type_and_more'),
        ('core', '0073_settings_split_min_length_settings_split_overlap_and_more'),
    ]

    operations = [
    ]
