# Generated by Django 4.2.18 on 2025-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_rename_ai_provider_settings_ai_model_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_ollama_base_model_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_ollama_embedding_model_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_ollama_url_valid',
            field=models.BooleanField(default=False),
        ),
    ]
