# Generated by Django 4.2.18 on 2025-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_gurutype_jira_count_limit_alter_datasource_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='zendesk_count_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='integration',
            name='zendesk_api_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='zendesk_subdomain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='zendesk_user_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WEBSITE', 'WEBSITE'), ('YOUTUBE', 'YOUTUBE'), ('GITHUB_REPO', 'GITHUB_REPO'), ('JIRA', 'JIRA'), ('ZENDESK', 'ZENDESK')], default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureddatasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('WEBSITE', 'Website'), ('YOUTUBE', 'Youtube'), ('GITHUB_REPO', 'Github Repo'), ('JIRA', 'Jira'), ('ZENDESK', 'Zendesk')], default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('DISCORD', 'DISCORD'), ('SLACK', 'SLACK'), ('GITHUB', 'GITHUB'), ('JIRA', 'JIRA'), ('ZENDESK', 'ZENDESK')], default='DISCORD', max_length=50),
        ),
    ]
