# Generated by Django 4.2.18 on 2025-04-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_gurutype_zendesk_count_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='zendesk_subdomain',
            new_name='zendesk_domain',
        ),
    ]
