# Generated by Django 4.2.18 on 2025-04-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_settings_is_ollama_base_model_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ollama_embedding_model_dimension',
            field=models.IntegerField(default=0),
        ),
    ]
