# Generated by Django 4.2.18 on 2025-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_settings_ollama_embedding_model_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='last_valid_embedding_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
