# Generated by Django 4.2.18 on 2025-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_rename_zendesk_subdomain_integration_zendesk_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ai_model_provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('OLLAMA', 'Ollama')], default='OPENAI', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_ollama_base_model_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_ollama_embedding_model_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_ollama_url_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='last_valid_embedding_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='last_valid_embedding_model_dimension',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_base_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_embedding_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_embedding_model_dimension',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
