# Generated by Django 4.2.18 on 2025-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_settings_ai_model_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='split_min_length',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='settings',
            name='split_overlap',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='settings',
            name='split_size',
            field=models.IntegerField(default=2000),
        ),
    ]
