# Generated by Django 4.2.18 on 2025-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_settings_last_valid_embedding_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='last_valid_embedding_model_dimension',
            field=models.IntegerField(default=0),
        ),
    ]
