# Generated by Django 4.2.18 on 2025-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_settings_split_min_length_settings_split_overlap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='confluence_count_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='integration',
            name='confluence_api_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='confluence_domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='confluence_user_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WEBSITE', 'WEBSITE'), ('YOUTUBE', 'YOUTUBE'), ('GITHUB_REPO', 'GITHUB_REPO'), ('JIRA', 'JIRA'), ('ZENDESK', 'ZENDESK'), ('CONFLUENCE', 'CONFLUENCE')], default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureddatasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('WEBSITE', 'Website'), ('YOUTUBE', 'Youtube'), ('GITHUB_REPO', 'Github Repo'), ('JIRA', 'Jira'), ('ZENDESK', 'Zendesk'), ('CONFLUENCE', 'Confluence')], default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('DISCORD', 'DISCORD'), ('SLACK', 'SLACK'), ('GITHUB', 'GITHUB'), ('JIRA', 'JIRA'), ('ZENDESK', 'ZENDESK'), ('CONFLUENCE', 'CONFLUENCE')], default='DISCORD', max_length=50),
        ),
    ]
