# Generated by Django 4.2.18 on 2025-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_gurutype_custom_instruction_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='gurubase_url',
            field=models.TextField(blank=True, default='http://localhost:8029', null=True),
        ),
    ]
