# Generated by Django 4.2.18 on 2025-04-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_settings_gurubase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('TURKISH', 'Turkish')], default='ENGLISH', max_length=100),
        ),
    ]
