# Generated by Django 4.2.18 on 2025-04-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_settings_gurubase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='custom_follow_up_prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='gurutype',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('TURKISH', 'Turkish')], default='ENGLISH', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='rerank',
            field=models.BooleanField(default=True),
        ),
    ]
