# Generated by Django 4.2.18 on 2025-04-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_remove_gurutype_github_repos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='github_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='github_details_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
