# Generated by Django 4.2.18 on 2025-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_gurutype_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='custom_follow_up_prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
