# Generated by Django 4.2.18 on 2025-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_gurutype_custom_follow_up_prompt_gurutype_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
