# Generated by Django 4.2.18 on 2025-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_gurutype_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='allow_dm',
            field=models.BooleanField(default=False),
        ),
    ]
