# Generated by Django 4.2.18 on 2025-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_gurutype_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='rerank',
        ),
        migrations.AddField(
            model_name='gurutype',
            name='rerank',
            field=models.BooleanField(default=True),
        ),
    ]
