# Generated by Django 4.2.18 on 2025-04-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_gurutype_custom_follow_up_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rerank',
            field=models.BooleanField(default=True),
        ),
    ]
