# Generated by Django 4.2.18 on 2025-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_settings_rerank_gurutype_rerank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WEBSITE', 'WEBSITE'), ('YOUTUBE', 'YOUTUBE'), ('GITHUB_REPO', 'GITHUB_REPO'), ('JIRA', 'JIRA'), ('ZENDESK', 'ZENDESK'), ('CONFLUENCE', 'CONFLUENCE'), ('EXCEL', 'EXCEL')], default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureddatasource',
            name='type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('WEBSITE', 'Website'), ('YOUTUBE', 'Youtube'), ('GITHUB_REPO', 'Github Repo'), ('JIRA', 'Jira'), ('ZENDESK', 'Zendesk'), ('CONFLUENCE', 'Confluence'), ('EXCEL', 'Excel')], default='PDF', max_length=50),
        ),
    ]
