# Generated by Django 4.2.18 on 2025-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_datasource_type_alter_featureddatasource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='excel_size_limit_mb',
            field=models.IntegerField(default=100),
        ),
    ]
