# Generated by Django 4.2.18 on 2025-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_gurutype_excel_size_limit_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurutype',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('TURKISH', 'Turkish'), ('DUTCH', 'Dutch')], default='ENGLISH', max_length=100),
        ),
    ]
