# Generated by Django 4.2.18 on 2025-05-08 10:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_add_language_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gurutype',
            name='language',
        ),
        migrations.AddField(
            model_name='gurutype',
            name='language',
            field=models.ForeignKey(default=core.models.get_default_language, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.language'),
        ),
    ]
