# Generated by Django 4.2.18 on 2025-04-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_thread_unique_together_remove_thread_binge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofcontextquestion',
            name='bot_context',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
