# Generated by Django 4.2.18 on 2025-04-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_outofcontextquestion_bot_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gurutype',
            name='github_repos',
        ),
        migrations.RemoveField(
            model_name='gurutype',
            name='index_repo',
        ),
    ]
