# Generated by Django 4.2.18 on 2025-04-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_datasource_github_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gurutype',
            name='github_details',
        ),
        migrations.RemoveField(
            model_name='gurutype',
            name='github_details_updated_date',
        ),
    ]
