# Generated by Django 4.2.18 on 2025-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_remove_gurutype_github_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurutype',
            name='allow_custom_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
