# Generated by Django 4.2.18 on 2025-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_gurutype_allow_custom_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='prompt_templates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
