name: Backend Beta Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/src/gurubase-backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Configure Dockerhub credentials
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: src/gurubase-backend
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.GURUBASE_BE_PCS_DOCKER_REPOSITORY }}:${{ github.event.inputs.version }}
        platforms: linux/amd64,linux/arm64
        file: src/gurubase-backend/Dockerfile

    - name: Image Tag
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "$IMAGE_TAG"
        echo "Image Tag: $IMAGE_TAG" >> $GITHUB_STEP_SUMMARY